<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UMRR3LS" name="NUGUAPP_003_홈.홈_01_홈카드" tests="12" failures="0" timestamp="1 Aug 2020 07:24:27 GMT" time="76.825" errors="1">
  <testcase name="TC_홈_001_11" time="5.961" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_07" time="5.731" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_01" time="20.148" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_03" time="5.209" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_09" time="5.972" classname="NUGUAPP_003_홈.홈_01_홈카드">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at NUGUAPP_003_홈.홈_01_홈카드.TC_홈_001_09(홈_01_홈카드.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC_홈_001_09 -->
  <testcase name="TC_홈_001_05" time="5.721" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_08" time="5.567" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_06" time="5.284" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_10" time="2.295" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_04" time="1.978" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_02" time="4.876" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
  <testcase name="TC_홈_001_12" time="8.083" classname="NUGUAPP_003_홈.홈_01_홈카드"/>
</testsuite> <!-- NUGUAPP_003_홈.홈_01_홈카드 -->
